#!/bin/sh
# check_pkg_payload.sh PKG — fail the build if the assembled .pkg is missing any install root a WORKING
# product needs. A dropped payload is invisible to the OS-floor + signature checks, so it must be asserted
# against the actual pkg contents here.
#
# Motivating regression (2026-07-24): the pkg's updater staging was gated on if(MT2_SPARKLE_FRAMEWORK), a
# cache variable the shared-cmake refactor DELETED. The gate silently went always-false, so 0.5.0 shipped
# with NO updater app and NO scheduled update-check agent -- "Check for Updates" did nothing and there was
# no background check either -- while every other gate (floor, signature, tests) stayed green.
set -u
PKG=${1:?usage: check_pkg_payload.sh PKG}
# 10.9's BSD mktemp needs an explicit template (-t); the GNU-style bare `mktemp -d` fails there.
tmp=$(mktemp -d -t check_pkg_payload 2>/dev/null) || { echo "FAIL: mktemp"; exit 1; }
trap 'rm -rf "$tmp"' EXIT
# --expand-full extracts each component's Payload as a real directory tree (not a cpio archive).
pkgutil --expand-full "$PKG" "$tmp/x" >/dev/null 2>&1 || { echo "FAIL: cannot expand $PKG"; exit 1; }

PAYLOAD=$(find "$tmp/x" -type d -name Payload | head -1)
[ -n "$PAYLOAD" ] || { echo "FAIL: no Payload directory in $PKG"; exit 1; }
SCRIPTS=$(find "$tmp/x" -type d -name Scripts | head -1)

fail=0
need()  { if [ -e "$PAYLOAD/$1" ]; then echo "PASS: $1"; else echo "FAIL: pkg payload missing $1"; fail=1; fi; }
needs() { if [ -n "$SCRIPTS" ] && [ -e "$SCRIPTS/$1" ]; then echo "PASS: script $1"; else echo "FAIL: pkg scripts missing $1"; fail=1; fi; }

# The updater surface -- exactly what the dead gate dropped. App + its scheduled update-check agent.
need  "Library/Application Support/ModernMavericks/Trackpad2Updater.app"
need  "Library/LaunchAgents/dev.modernmavericks.voodooinputmavericks.updatecheck.plist"
# Core driver surface.
need  "usr/local/lib/voodooinputmavericks/VoodooInputMavericks.kext"
need  "usr/local/sbin/voodooinputmavericks-run"
need  "Library/LaunchDaemons/dev.modernmavericks.voodooinputmavericks.plist"
# Prefpane companion (staged in the payload; the postinstall installs it into the SIMBL Plugins dir).
need  "usr/local/share/voodooinputmavericks/VoodooInputMavericksPane.bundle"
# Install scripts (sit beside the component Payload). agent-load.sh is generated by stage_updater.sh and
# sourced by the postinstall to load the update-check agent; migrate_autocheck.sh carries the opt-in.
needs postinstall
needs agent-load.sh
needs migrate_autocheck.sh

[ "$fail" = 0 ] && echo "ALL PASS: pkg payload complete ($PKG)" || echo "PKG PAYLOAD INCOMPLETE ($PKG)"
exit $fail
